param(
    [string]$ProfilePath = (Join-Path $PSScriptRoot "TradeNet.SplitRouting.psd1"),
    [string]$ExamplePath = (Join-Path $PSScriptRoot "TradeNet.SplitRouting.example.psd1"),
    [string]$OutputPath
)

[Console]::InputEncoding = [System.Text.UTF8Encoding]::new()
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Quote-YamlString {
    param([string]$Value)

    return "'{0}'" -f ($Value -replace "'", "''")
}

function Add-YamlKeyValue {
    param(
        [System.Collections.Generic.List[string]]$Lines,
        [string]$Key,
        [string]$Value,
        [int]$Indent = 0
    )

    $prefix = (" " * $Indent)
    $Lines.Add(("{0}{1}: {2}" -f @($prefix, $Key, $Value)))
}

function Add-YamlList {
    param(
        [System.Collections.Generic.List[string]]$Lines,
        [string]$Key,
        [object[]]$Values,
        [int]$Indent = 0
    )

    $prefix = (" " * $Indent)
    $Lines.Add(("{0}{1}:" -f @($prefix, $Key)))
    foreach ($value in $Values) {
        $Lines.Add(("{0}  - {1}" -f @($prefix, (Quote-YamlString -Value ([string]$value)))))
    }
}

function Test-PlaceholderValue {
    param([string]$Value)

    return $Value -like "__FILL_*__"
}

if (-not (Test-Path -LiteralPath $ProfilePath)) {
    throw "Profile not found: $ProfilePath`nCreate TradeNet.SplitRouting.psd1 based on $ExamplePath before building."
}

$profile = Import-PowerShellDataFile -Path $ProfilePath

if (-not $OutputPath) {
    $OutputPath = $profile.OutputConfigPath
}

$stateDir = Join-Path $PSScriptRoot "state"
$statePath = Join-Path $stateDir "split-routing-state.json"
if (-not (Test-Path -LiteralPath $stateDir)) {
    New-Item -ItemType Directory -Path $stateDir -Force | Out-Null
}

if (-not $profile.WireGuard.PrivateKey -or (Test-PlaceholderValue -Value $profile.WireGuard.PrivateKey)) {
    throw "WireGuard.PrivateKey is not set in $ProfilePath"
}

if (-not $profile.WireGuard.PublicKey -or (Test-PlaceholderValue -Value $profile.WireGuard.PublicKey)) {
    throw "WireGuard.PublicKey is not set in $ProfilePath"
}

$outputDir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# Generated by Build-TradeNetMihomoConfig.ps1")
$lines.Add("# Review the file before enabling split-routing mode.")
$lines.Add("")

Add-YamlKeyValue -Lines $lines -Key "mixed-port" -Value ([string]$profile.MixedPort)
Add-YamlKeyValue -Lines $lines -Key "allow-lan" -Value "false"
Add-YamlKeyValue -Lines $lines -Key "mode" -Value "rule"
Add-YamlKeyValue -Lines $lines -Key "log-level" -Value (Quote-YamlString -Value $profile.LogLevel)
Add-YamlKeyValue -Lines $lines -Key "ipv6" -Value ($(if ($profile.DNS.IPv6) { "true" } else { "false" }))
Add-YamlKeyValue -Lines $lines -Key "external-controller" -Value (Quote-YamlString -Value $profile.Controller)
$lines.Add("")

$lines.Add("dns:")
Add-YamlKeyValue -Lines $lines -Key "enable" -Value ($(if ($profile.DNS.Enable) { "true" } else { "false" })) -Indent 2
Add-YamlKeyValue -Lines $lines -Key "ipv6" -Value ($(if ($profile.DNS.IPv6) { "true" } else { "false" })) -Indent 2
Add-YamlKeyValue -Lines $lines -Key "enhanced-mode" -Value (Quote-YamlString -Value $profile.DNS.EnhancedMode) -Indent 2
Add-YamlList -Lines $lines -Key "nameserver" -Values $profile.DNS.NameServers -Indent 2
$lines.Add("")

$lines.Add("tun:")
Add-YamlKeyValue -Lines $lines -Key "enable" -Value ($(if ($profile.TUN.Enable) { "true" } else { "false" })) -Indent 2
Add-YamlKeyValue -Lines $lines -Key "stack" -Value (Quote-YamlString -Value $profile.TUN.Stack) -Indent 2
Add-YamlKeyValue -Lines $lines -Key "auto-route" -Value ($(if ($profile.TUN.AutoRoute) { "true" } else { "false" })) -Indent 2
Add-YamlKeyValue -Lines $lines -Key "strict-route" -Value ($(if ($profile.TUN.StrictRoute) { "true" } else { "false" })) -Indent 2
Add-YamlList -Lines $lines -Key "dns-hijack" -Values $profile.TUN.DnsHijack -Indent 2
$lines.Add("")

$lines.Add("proxies:")
$lines.Add(("  - name: {0}" -f (Quote-YamlString -Value $profile.WireGuard.Name)))
Add-YamlKeyValue -Lines $lines -Key "type" -Value (Quote-YamlString -Value "wireguard") -Indent 4
Add-YamlKeyValue -Lines $lines -Key "server" -Value (Quote-YamlString -Value $profile.WireGuard.Server) -Indent 4
Add-YamlKeyValue -Lines $lines -Key "port" -Value ([string]$profile.WireGuard.Port) -Indent 4
Add-YamlKeyValue -Lines $lines -Key "ip" -Value (Quote-YamlString -Value $profile.WireGuard.IpCidr) -Indent 4
Add-YamlKeyValue -Lines $lines -Key "private-key" -Value (Quote-YamlString -Value $profile.WireGuard.PrivateKey) -Indent 4
Add-YamlKeyValue -Lines $lines -Key "public-key" -Value (Quote-YamlString -Value $profile.WireGuard.PublicKey) -Indent 4
Add-YamlKeyValue -Lines $lines -Key "mtu" -Value ([string]$profile.WireGuard.MTU) -Indent 4
Add-YamlKeyValue -Lines $lines -Key "udp" -Value ($(if ($profile.WireGuard.UDP) { "true" } else { "false" })) -Indent 4
Add-YamlKeyValue -Lines $lines -Key "persistent-keepalive" -Value ([string]$profile.WireGuard.PersistentKeepalive) -Indent 4
Add-YamlList -Lines $lines -Key "allowed-ips" -Values $profile.WireGuard.AllowedIPs -Indent 4
$lines.Add("")

$lines.Add("proxy-groups:")
$lines.Add("  - name: 'TradeNet'")
$lines.Add("    type: select")
$lines.Add("    proxies:")
$lines.Add(("      - {0}" -f (Quote-YamlString -Value $profile.WireGuard.Name)))
$lines.Add("      - 'DIRECT'")
$lines.Add("")

$lines.Add("rules:")
foreach ($name in $profile.AppRules.Direct) {
    $lines.Add(("  - PROCESS-NAME,{0},DIRECT" -f $name))
}

foreach ($name in $profile.AppRules.TradeNet) {
    $lines.Add(("  - PROCESS-NAME,{0},TradeNet" -f $name))
}

$lines.Add(("  - MATCH,{0}" -f $profile.DefaultAction))

$yaml = [string]::Join([Environment]::NewLine, $lines)
Set-Content -Path $OutputPath -Value $yaml -Encoding UTF8

$validationPassed = $false
$validationMessage = "Mihomo validation skipped."
$mihomoExe = $profile.MihomoExe

if ($mihomoExe -and (Test-Path -LiteralPath $mihomoExe)) {
    $validationOutput = (& $mihomoExe -t -f $OutputPath 2>&1 | Out-String).Trim()
    $validationPassed = $LASTEXITCODE -eq 0
    $validationMessage = if ($validationOutput) { $validationOutput } else { "Mihomo validation completed." }
    if (-not $validationPassed) {
        $state = [ordered]@{
            GeneratedAt       = (Get-Date).ToString("o")
            ProfilePath       = $ProfilePath
            OutputPath        = $OutputPath
            MihomoExe         = $mihomoExe
            ValidationPassed  = $validationPassed
            ValidationMessage = $validationMessage
        }
        $state | ConvertTo-Json -Depth 4 | Set-Content -Path $statePath -Encoding UTF8
        throw "Mihomo validation failed: $validationMessage"
    }
} elseif ($mihomoExe) {
    $validationMessage = "Mihomo executable not found: $mihomoExe"
}

$state = [ordered]@{
    GeneratedAt       = (Get-Date).ToString("o")
    ProfilePath       = $ProfilePath
    OutputPath        = $OutputPath
    MihomoExe         = $mihomoExe
    ValidationPassed  = $validationPassed
    ValidationMessage = $validationMessage
}
$state | ConvertTo-Json -Depth 4 | Set-Content -Path $statePath -Encoding UTF8

Write-Host "Generated: $OutputPath" -ForegroundColor Green
Write-Host "Validate with:" -ForegroundColor Gray
Write-Host "  `"$($profile.MihomoExe)`" -t -f `"$OutputPath`"" -ForegroundColor Gray
Write-Host "State: $statePath" -ForegroundColor Gray
