from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml


def load_yaml(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if data is None:
        return {}
    if not isinstance(data, dict):
        raise SystemExit(f"YAML root must be a mapping: {path}")
    return data


def write_yaml(path: Path, data: dict[str, Any], tradenet_path: Path) -> None:
    header = "\n".join(
        [
            "# Generated by Build-TradeNetClashConfig.py",
            f"# TradeNet source: {tradenet_path}",
            "",
        ]
    )
    body = yaml.safe_dump(
        data,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
        width=4096,
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(header + body, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a pure TradeNet Clash config from the generated split-routing YAML.")
    parser.add_argument("--tradenet-config", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    tradenet_path = Path(args.tradenet_config).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()

    tradenet = load_yaml(tradenet_path)
    write_yaml(output_path, tradenet, tradenet_path)

    print(f"Generated: {output_path}")
    print(f"TradeNet source: {tradenet_path}")
    print(f"Proxy count: {len(tradenet.get('proxies', []))}")
    print(f"Group count: {len(tradenet.get('proxy-groups', []))}")
    print(f"Rule count: {len(tradenet.get('rules', []))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
